require('core.config.treesitter')
require('core.config.lualine')
require('core.config.telescope')
require('core.config.tokyo')
require('core.config.yank-highlight')
require('core.config.cmp')
require('core.config.lsp')
